# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20150328_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='partner',
            name='texte',
            field=models.TextField(blank=True, null=True, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
    ]
