# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_brand_visible'),
        ('partners', '0003_auto_20160704_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.Brand', verbose_name='Marque'),
        ),
    ]
